// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdkqE14Mwmakdj_-MHBSg2ZbB0NrsC-JA',
    appId: '1:687791599216:web:135f07bc7d954ace6d8eb5',
    messagingSenderId: '687791599216',
    projectId: 'thirukkural-learning',
    authDomain: 'thirukkural-learning.firebaseapp.com',
    storageBucket: 'thirukkural-learning.firebasestorage.app',
    measurementId: 'G-J1VEDZ2E5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Zp0eXKBTk6zQPoxWuCvBJKEZJmjNXVQ',
    appId: '1:687791599216:android:c60522adaaca3b3e6d8eb5',
    messagingSenderId: '687791599216',
    projectId: 'thirukkural-learning',
    storageBucket: 'thirukkural-learning.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD95dsrlRd5U93odeclqaDi7HivV6jfuMU',
    appId: '1:687791599216:ios:011102734cbf6f456d8eb5',
    messagingSenderId: '687791599216',
    projectId: 'thirukkural-learning',
    storageBucket: 'thirukkural-learning.firebasestorage.app',
    iosBundleId: 'com.thirukkural.journey.thirukkuralJourney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD95dsrlRd5U93odeclqaDi7HivV6jfuMU',
    appId: '1:687791599216:ios:011102734cbf6f456d8eb5',
    messagingSenderId: '687791599216',
    projectId: 'thirukkural-learning',
    storageBucket: 'thirukkural-learning.firebasestorage.app',
    iosBundleId: 'com.thirukkural.journey.thirukkuralJourney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdkqE14Mwmakdj_-MHBSg2ZbB0NrsC-JA',
    appId: '1:687791599216:web:86b12470d44e8c3c6d8eb5',
    messagingSenderId: '687791599216',
    projectId: 'thirukkural-learning',
    authDomain: 'thirukkural-learning.firebaseapp.com',
    storageBucket: 'thirukkural-learning.firebasestorage.app',
    measurementId: 'G-3CNWFC7Y3V',
  );
}
