#!/usr/bin/env python3
"""
Script to generate child-friendly explanations for Thirukkural verses.
This creates explanations suitable for 6-8 year old learners based on the English meanings.
"""

import json
import re

def simplify_for_children(kural_no, english_explanation):
    """
    Generate child-friendly explanations based on the English meaning.
    This is a template-based approach for common themes in Thirukkural.
    """
    
    # Dictionary of simplified explanations for specific kurals
    # This would ideally be generated by AI, but we'll create templates for common themes
    
    simplified_explanations = {
        # Chapter 1: Praise of God (1-10)
        1: "Just like 'A' is the first letter you learn in school, God is the beginning of everything in this world! When you start learning, you begin with 'A'. Similarly, everything in the universe starts with God.",
        
        2: "Learning is wonderful, but it's even more special when we remember to thank God! It's like learning to ride a bike - it's fun, but even better when you share your joy with someone who cares about you.",
        
        3: "When we think about God and remember His goodness, we become happy and strong! It's like having a superhero friend who always helps you do your best.",
        
        4: "People who remember God don't have to worry about bad things happening. It's like having an umbrella in the rain - you stay dry and safe!",
        
        5: "When we praise God and think good thoughts, bad things can't stick to us. It's like having a special shield that keeps away all the yucky stuff!",
        
        # Add more as needed - this is a template
    }
    
    # If we have a specific explanation, use it
    if kural_no in simplified_explanations:
        return simplified_explanations[kural_no]
    
    # Otherwise, create a generic child-friendly version based on keywords
    explanation = english_explanation.lower()
    
    # Pattern matching for common themes
    if 'god' in explanation or 'eternal' in explanation:
        return f"This kural teaches us about God and how important it is to remember Him. Just like we remember our parents who love us, we should remember God who created everything!"
    
    elif 'learn' in explanation or 'knowledge' in explanation or 'wisdom' in explanation:
        return f"This kural tells us that learning is very important! Just like you learn new things in school every day, we should always keep learning to become smarter and kinder."
    
    elif 'virtue' in explanation or 'good' in explanation or 'righteous' in explanation:
        return f"This kural teaches us to be good and kind. When we do good things and help others, we feel happy inside, just like when you share your toys with friends!"
    
    elif 'family' in explanation or 'home' in explanation or 'wife' in explanation or 'children' in explanation:
        return f"This kural is about family and home. Our family loves us and takes care of us, just like a bird's nest keeps baby birds safe and warm!"
    
    elif 'friend' in explanation or 'friendship' in explanation:
        return f"This kural talks about friends! Good friends are like treasures - they play with you, help you, and make you smile. We should choose kind friends and be kind friends too!"
    
    elif 'king' in explanation or 'ruler' in explanation or 'govern' in explanation:
        return f"This kural is about leaders and how they should be fair and kind. Just like a good class monitor helps everyone, good leaders take care of all people!"
    
    elif 'wealth' in explanation or 'money' in explanation or 'rich' in explanation:
        return f"This kural teaches us about money and things we own. It's good to have what we need, but it's even better to share with others who don't have enough!"
    
    elif 'poor' in explanation or 'poverty' in explanation or 'beg' in explanation:
        return f"This kural reminds us to help people who don't have enough. When we share our lunch with a friend who forgot theirs, we're being kind and helpful!"
    
    elif 'love' in explanation or 'affection' in explanation:
        return f"This kural is about love! Love makes us feel warm and happy, like a big hug from someone special. We should show love to our family and friends!"
    
    elif 'anger' in explanation or 'wrath' in explanation:
        return f"This kural teaches us not to get too angry. When we're angry, we should take deep breaths and calm down, just like counting to ten before we speak!"
    
    elif 'truth' in explanation or 'honest' in explanation or 'lie' in explanation:
        return f"This kural tells us to always tell the truth! Being honest is like being a superhero - it takes courage, but it's always the right thing to do!"
    
    elif 'harm' in explanation or 'hurt' in explanation or 'evil' in explanation:
        return f"This kural teaches us not to hurt others. We should be gentle and kind, just like we want others to be gentle and kind to us!"
    
    elif 'agriculture' in explanation or 'farm' in explanation or 'plow' in explanation:
        return f"This kural is about farming and growing food! Farmers work hard to grow the food we eat. We should thank them and never waste food!"
    
    else:
        # Generic fallback
        return f"This kural teaches us an important lesson about life. It helps us understand how to be better people and live happily with others!"

def generate_children_explanations():
    """Generate child-friendly explanations for all kurals."""
    
    # Read the original kurals data
    with open('/Users/kavya.d/Documents/Tirukkural App/Thirukkural Learning/assets/data/kurals.json', 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    children_explanations = []
    
    for feature in data['features']:
        props = feature['properties']
        kural_no = props['kural_no']
        english_explanation = props['kuralvilakam_english']
        
        # Generate child-friendly explanation
        child_explanation = simplify_for_children(kural_no, english_explanation)
        
        children_explanations.append({
            'kural_no': kural_no,
            'child_explanation': child_explanation,
            'original_english': english_explanation
        })
    
    # Save to a new JSON file
    output = {
        'metadata': {
            'description': 'Child-friendly explanations for Thirukkural verses',
            'target_age_group': '6-8 years',
            'total_kurals': len(children_explanations),
            'generated_date': '2025-12-05'
        },
        'explanations': children_explanations
    }
    
    with open('/Users/kavya.d/Documents/Tirukkural App/Thirukkural Learning/assets/data/children_explanations.json', 'w', encoding='utf-8') as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    
    print(f"✅ Generated {len(children_explanations)} child-friendly explanations!")
    print(f"📁 Saved to: children_explanations.json")

if __name__ == '__main__':
    generate_children_explanations()
